function [new_labels, classes] = change_class_labels(labels, ch)

switch ch
  case 1
    type = 'Reynolds & Antoniou (2003), 7 classes';
    classes = {{'b', 'd', 'g', 'p', 't', 'k', 'jh', 'ch'}, ...
      {'s', 'sh', 'z', 'f', 'th', 'v', 'dh', 'hh'}, ...
      {'m', 'n', 'ng'}, ...
      {'l', 'r', 'er', 'w', 'y'}, ...
      {'iy', 'ih', 'eh', 'ae', 'aa', 'ah', 'uh', 'uw'}, ...
      {'ey', 'aw', 'ay', 'oy', 'ow'}, ...
      {'bcl', 'dcl', 'gcl', 'pcl', 'tcl', 'kcl', 'epi', 'pau', 'h#', 'dx'}};

  case 2
    type = 'Halberstadt (1998), 3 classes';
    classes_full = {{'aa', 'ae', 'ah', 'ao', 'aw', 'ax', 'ax-h', 'axr', 'ay', 'eh', 'er', 'ey', 'ih', ...
    'ix', 'iy', 'ow', 'oy', 'uh', 'uw', 'ux', 'el', 'l', 'r', 'w', 'y'},...
    {'em', 'en', 'eng', 'm', 'n', 'ng', 'nx', 'dx'}, ...
    {'s', 'z', 'sh', 'zh', 'ch', 'jh'}, ...
    {'v', 'f', 'dh', 'th', 'hh', 'hv'}, ...
    {'b', 'd', 'g', 'p', 't', 'k'}, ...
    {'bcl', 'dcl', 'gcl', 'pcl', 'tcl', 'kcl', 'epi', 'pau', 'h#'}};
    classes = {[classes_full{1}, classes_full{2}], ...
      [classes_full{3}, classes_full{4}, classes_full{5}], ...
      classes_full{6}};

  case 3
    type = 'Lee & Hon (1989), 36 classes';
    classes = {{'aa', 'ao',}, ...
      {'ah', 'ax', 'ax-h'}, ...
      {'er', 'axr'}, ...
      {'hh', 'hv'}, ...
      {'ih', 'ix'}, ...
      {'l', 'el'}, ...
      {'sh', 'zh'}, ...
      {'uw', 'ux'}, ...
      {'pcl', 'tcl', 'kcl', 'bcl', 'dcl', 'gcl', 'h#', 'pau', 'epi'}, ...
      {'b'}, ...
      {'d'}, ...
      {'g'}, ...
      {'p'}, ...
      {'t'}, ...
      {'k'}, ...
      {'jh'}, ...
      {'ch'}, ...
      {'s'}, ...
      {'z'}, ...
      {'f'}, ...
      {'th'}, ...
      {'v'}, ...
      {'dh'}, ...
      {'r'}, ...
      {'w'}, ...
      {'y'}, ...
      {'iy'}, ...
      {'eh'}, ...
      {'ae'}, ...
      {'uh'}, ...
      {'ey'},  ...
      {'aw'},  ...
      {'ay'},  ...
      {'oy'},  ...
      {'ow'}, ...
      {'dx'}};
  otherwise
    type = 'TIMIT phonemas, 61 classes';
    classes = unique(labels{3});
    if numel(classes) ~= 61
        msg = [inputname(1),' isnt complete (', num2str(numel(classes)), ' != 61 phonemas).'];
      if nargout == 2
        msg = [msg(1:end-1), ' which causes wrong output of the classes '];
        error(msg)
      else
        warning(msg)
      end
    end
end

label_vector = zeros(size(labels{3}));
for ind = 1:numel(labels{3})
  for ind2 = 1:numel(classes)
    if ~isempty(find(strcmp(classes{ind2}, labels{3}{ind})))
      label_vector(ind) = ind2;
      break;
    else
      % So we don't care about these, we must affect events in this label and then
      % explicitely discard this label.
      label_vector(ind) = 0;
    end
  end
end

new_labels = {labels{1}, labels{2}, label_vector};
