function td_data = load_event2D_64bit_ts(filename)
% td_data = load_event2D_64bit_ts(filename)
%
% Loads data from files generated by the StreamLogger consumer for any type
% of event. This function only read (t, addr) and discard other fields (if
% any) of events.
% timestamps are in uS
% td_data is a structure containing the fields ts and addr
%

ev = load_addr_data_64bit_ts(filename);
td_data = convert_addr_to_event2D(ev);
end

function event2D_data = convert_addr_to_event2D(td_data)

xmask = hex2dec('000001FF');
ymask = hex2dec('0001FE00');
polmask = hex2dec('00020000');

% Maybe use Hamming weight instead?
xshift=0; % bits to shift x to right
yshift=9; % bits to shift y to right
polshift=17; % bits to shift p to right

event2D_data.ts = td_data.ts;
event2D_data.x=uint8(bitshift(bitand(td_data.addr,xmask),-xshift)); % x addresses
event2D_data.y=uint8(bitshift(bitand(td_data.addr,ymask),-yshift)); % y addresses
event2D_data.p=boolean(bitshift(bitand(td_data.addr,polmask),-polshift)); % 1 for ON, 0 for OFF
end
