classes = {'aa', 'ao', 'q', ...
  'ah', 'ax', 'ax-h', ...
  'er', 'axr', ...
  'hh', 'hv', ...
  'ih', 'ix', ...
  'l', 'el', ...
  'm', 'em', ...
  'n', 'en', 'nx', ...
  'ng', 'eng', ...
  'sh', 'zh', ...
  'uw', 'ux', ...
  'pcl', 'tcl', 'kcl', 'bcl', 'dcl', 'gcl', 'h#', 'pau', 'epi', ...
  'b', 'd', 'g', 'p', 't', 'k', 'jh', 'ch', 's', 'z', 'f', ...
  'th', 'v', 'dh', 'r', 'w', 'y', 'iy', 'eh', ...
  'ae',  'uh',  'ey',  'aw',  'ay',  'oy',  'ow', 'dx'};
classes = unique(classes);


for ind = 1:numel(label_test2{3})
    label_test2{3}(ind) = classes(str2num(label_test2{3}{ind}));
end

